function sim_params = my_set_sim_param()
% MY_SET_SIM_PARAM 시뮬레이션 파라미터들을 생성하고 구조체로 반환
% 사용법: 
%   sim_params = my_set_sim_param(); % 구조체로 받기
%   my_set_sim_param(); % 작업 공간에 직접 변수들 생성


% 파라미터 정의
Vsmax = 60;
Stop_Time = 1;
J = 0.045;
B = 0.0001;
TL = 20;

P = 24;
Rs = 2;
Lds = 30.0e-3; %[H] 
Lqs = 40.0e-3; %[H]
Lamf = 0.12; %[Wb]

Wrpm_rated = 400;
Te_rated = 20;
Is_rated = 10;

Wrm_rated = Wrpm_rated * 2*pi/60;
Wr_rated = Wrm_rated * P;

Wcc = 100 * 2*pi;
Kpc = Lds * Wcc;
Kic = Rs * Wcc;

Kt = 1.5 * P * Lamf;
Wsc = 2*pi*5;
Kps = J * Wsc / Kt;
Kis = J * Wsc^2 / 5 / Kt;
Kas = 1 / Kps;

sample_count = 100001;

% 모든 변수들을 구조체에 저장
sim_params = struct(...
    'Stop_Time', Stop_Time, ...
    'J', J, ...
    'B', B, ...
    'TL', TL, ...
    'P', P, ...
    'Rs', Rs, ...
    'Lds', Lds, ...
    'Lqs', Lqs, ...
    'Lamf', Lamf, ...
    'Wrpm_rated', Wrpm_rated, ...
    'Te_rated', Te_rated, ...
    'Is_rated', Is_rated, ...
    'Wrm_rated', Wrm_rated, ...
    'Wr_rated', Wr_rated, ...
    'Wcc', Wcc, ...
    'Kpc', Kpc, ...
    'Kic', Kic, ...
    'Kt', Kt, ...
    'Wsc', Wsc, ...
    'Kps', Kps, ...
    'Kis', Kis, ...
    'Kas', Kas, ...
    'sample_count', sample_count, ...
    'Vsmax', Vsmax);

% 작업 공간에 개별 변수들로도 저장하려면 (선택사항)
if nargout == 0
    names = fieldnames(sim_params);
    for i = 1:length(names)
        assignin('base', names{i}, sim_params.(names{i}));
    end
end

end